### ISSUE TITLE
Pull Request not working

### ISSUE THREAD

**Issue by KatieLars** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#1]
I passed all my tests, but my pull request isn't registering, saying the lesson was completed

**Comment by curiositypaths** [comment]
Thanks for [contributing](http://help.learn.co/improving-learn) to the [Learn](http://learn.co/) curriculum!

Bear in mind that [raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform. The first place to turn for most issues is the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) feature on [Learn](http://learn.co/). For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

### Suggesting new curriculum 📝
If you have suggestions for new content that you think would improve the flow or coverage of the Learn curriculum, that's awesome, but keep the following in mind:
- The curriculum is not intended to be an exhaustive suite that covers every single topic in Ruby, JavaScript, etc.
- It might be a good idea to first check with the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) and/or peers who recently completed the same material to see if they noticed similar deficiencies.

### Reporting bugs 🐛
If you'd like to [report a bug](http://help.learn.co/improving-learn/reporting-bugs/reporting-a-bug) about the [Learn IDE](http://help.learn.co/the-learn-ide), the [lights not working on Learn](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green), or any other issue with the site, please consult the [Learn Help Center](http://help.learn.co/) and/or escalate the issue via [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). If you are unable to access Ask a Question or your track is not supported by the Technical Coaches, please send us a message via the [Intercom](https://user-images.githubusercontent.com/17556281/27602126-b825ff3a-5b3f-11e7-9dcd-0ced7e507bfb.png) widget on any [Help Center](http://help.learn.co/) page.

As always thank you for contributing! 💙
