### ISSUE TITLE
Test not picking up presence of Math.random

### ISSUE THREAD

**Issue by lauraroyle** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#13]
I think there is an error in the test where it is not taking over for Math.random?

This code is failing when I'm not sure it should:

function tailsNeverFails() {
  let number = 0;

  while (Math.random() >= 0.5) {
    number++;
  }
  return `You got ${number} tails in a row!`;
}

**Comment by maxwellbenton** [comment]
Hi @lauraroyle, 

Thank you for spotting this and providing feedback. We've been receiving reports of issues related to Math.random for some students and have updated this lesson to no longer rely on it, so this issue should now be resolved.

Thanks again!
