### ISSUE TITLE
Error: Cannot find module 'jsdom/lib/old-api'

### ISSUE THREAD

**Issue by cdallasanta** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#17]
On a fresh copy of this lab, running `learn` encounters the following error:

```
  1) "before all" hook:
     Error: Cannot find module 'jsdom/lib/old-api'
      at require (internal/module.js:11:18)
      at Context.<anonymous> (node_modules/mocha-jsdom/index.js:53:5)
```

Solution for me is the same provided by @ivalentine on another lab [here](https://github.com/learn-co-curriculum/js-what-is-a-test-lab/issues/11).

> Looks like this is a broader issue affecting multiple JS labs. The solution is to change this line in package.json…
> 
> `"mocha-jsdom": "^1.1.0"`,
> 
> …to this…
> 
> `"mocha-jsdom": "~1.1.0"`,
> 
> …then run `npm install`.

**Comment by sgharms** [comment]
@cdallasanta 

As you can [see here](https://github.com/learn-co-curriculum/js-looping-and-iteration-looping-code-along/blob/master/package.json#L36) we have the change, just as you suggest, in place.

We'll make sure this replication is up-to-date in the LMS. Thank you.
