### ISSUE TITLE
Incorrect test code for Re:Coded Front End Web Development curriculum

### ISSUE THREAD

**Issue by lizbur10** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#19]
For the Re:Coded curriculum, the test code in indexTest.js does not match the instructions for the code-along and is different from the (correct) test code in the canonical branch. 

#staff

**Comment by sgharms** [comment]
Since this isn't a text-of-the-curriculum issue, I'm going to move this to a JIRA issue (internal).
