### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by angeleenmcw** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#30]
I am having issues testing the code. I keep getting $ mocha --timeout 5000 -R mocha multi --reporter-options spec=-, json=.results.json

**Comment by lizbur10** [comment]
Hi there! I'm so sorry to hear you were having this problem! Presumably you were able to find a solution to this issue and move forward - my apologies for the inconvenience and for the delay in responding.

💙
