### ISSUE TITLE
Another solution in ES6

### ISSUE THREAD

**Issue by bolloland** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#34]
Hi.

I noticed that the following code passes the 2nd (while) test in Console, but not through the test. 
I get an error message: **"ReferenceError: countDown is not defined"**

const countDown = (i) => {
    while (i >= 0) {
        console.log(i); 
        i--
    }
}

Looks like the test is only looking for "countDown()", but  you should allow for ES6 syntax as well. Thanks!
---

## Link to Canvas

Add a link to the assignment in Canvas here.

## Describe the bug

Write a clear and concise description of what the bug is. Include the file and
line number(s) if possible.

## What is the expected behavior?

Write a clear and concise description of what you expected to happen.

## Screenshots

If applicable, attach screenshots to help explain your problem.

## What OS are you using?

- [ ] OS X
- [ ] WSL
- [ ] Linux

**Comment by lizbur10** [comment]
Hi there! Thank you for posting this issue!

I am not able to recreate this issue so I am closing it. I used the code you posted above and it passed both tests. It is likely that you had a syntax error somewhere else in your code that was keeping JavaScript from recognizing your function.

Thanks for contributing to the Flatiron School curriculum. 💙
