### ISSUE TITLE
formatting typo at 'Loop Body'

### ISSUE THREAD

**Issue by above9Sq** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#7]
**Current layout:**

- Iteration

- A statement executed at the end of each iteration. Typically, this will involve incrementing or decrementing a counter, bringing the loop ever closer to completion. - Loop body

- Code that runs on each pass through the loop.

**Proposed layout:**

- Iteration

- A statement executed at the end of each iteration. Typically, this will involve incrementing or decrementing a counter, bringing the loop ever closer to completion. 

- Loop body

- Code that runs on each pass through the loop.

**Comment by sgharms** [comment]
Thanks! Updated!
