### ISSUE TITLE
Browser alert that Test site is Dangerous

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#8]
Hey there--when I went to copy and paste the test URL, I was alerted by Chrome that the test site was Dangerous. Not sure if this is useful information, I just wanted to let you know.

**Comment by sgharms** [comment]
Noted. We'll look into it.

**Comment by drakeltheryuujin** [comment]
Hi @helloamandamurphy,

I wasn’t able to find a test URL in this lab. Did you mean to open this issue on a different lab?
If so, please open the issue in the corresponding repo. If I'm misunderstanding this request, please reopen the issue and give a bit more clarification on where in the lesson this URL exists. 

Thank you for your contribution 💙

**Comment by helloamandamurphy** [comment]
Hey Kellye, when I ran "learn" in the terminal, the terminal provided a URL--mine looked something like this: "http://67.205.152.27:41928." When I copy and pasted that into my browser, I got a red warning screen from Chrome saying that the site was dangerous and I shouldn't proceed because my passwords, personal identity, and credit card information could be at risk. I thought I had messed something up, but I reopened the lab and tried the link again and it said the same thing multiple times.
