### ISSUE TITLE
Browser alert that Test site is Dangerous (Re-opening)

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/js-looping-and-iteration-looping-code-along#9]
Hey Kellye, when I ran "learn" in the terminal for this lab, the terminal provided a URL--mine looked something like this: "http://67.205.152.27:41928." When I copy and pasted that into my browser, I got a red warning screen from Chrome saying that the site was dangerous, phishing had been detected, and I shouldn't proceed because my passwords, personal identity, and credit card information could be at risk. I thought I had messed something up, but I reopened the lab and tried the link again and it said the same thing multiple times. 

Maybe it was my internet connection, but it was the first time I encountered it working from home (which is common for me) and I had worked on several labs last night, and this was the only lab with which I experienced the issue.

See the image below.

<img width="1440" alt="screen shot 2019-02-28 at 7 53 22 pm" src="https://user-images.githubusercontent.com/40896525/53657168-60f98d00-3c23-11e9-8f20-88d343d82834.png">

**Comment by sgharms** [comment]
@helloamandamurphy 

This is very interesting, but the issue appears to be with learn itself. We can't fix this via the Curriculum. Could you please report this as recommended here?

> To report a bug please use the Ask A Question feature on Learn.co and a Technical Coach will assist you. If the Technical Coach is unable to solve the issue, they will log a ticket with our Support team on your behalf. 

http://help.learn.co/technical-support/improving-learn/reporting-a-bug

That will get you a platform support request so we can make sure to drive this to resolution.

Thanks!
